
--creating tables

CREATE TABLE Products(
		ID int PRIMARY KEY IDENTITY(1,1),
		PName Varchar(50),
		Price MONEY
);

CREATE TABLE Customers(
		ID int PRIMARY KEY IDENTITY(1,1),
		Firstname Varchar(50),
		Lastname Varchar(50),
		CardNumber Varchar(50)
);

CREATE TABLE Orders(
		ID int PRIMARY KEY IDENTITY(1,1),
		ProductID int NOT NULL FOREIGN KEY REFERENCES Products(ID),
		CustomerID int NOT NULL FOREIGN KEY REFERENCES Customers(ID)
);


-- Inserting three records each into tables 

INSERT INTO Products (PName, Price)
	VALUES
		('Blackberry', 350.00),
		('Microwave', 500.00),
		('Dishmaker', 1200.00);

INSERT INTO Customers(Firstname, Lastname, CardNumber)
	VALUES
		('Jay', 'Z', '49775050778478'),
		('Chief', 'Keef', '95746338372279'),
		('Meek', 'Mill', '23684946378979');

INSERT INTO Orders(ProductID, CustomerID)
	VALUES
		((SELECT ID from Products Where PName = 'Blackberry'),
		(SELECT ID from Customers Where Firstname = 'Jay')
		);

INSERT INTO Orders(ProductID, CustomerID)
	VALUES
		((SELECT ID from Products Where PName = 'Microwave'),
		(SELECT ID from Customers Where Firstname = 'Chief')
		);
	
INSERT INTO Orders(ProductID, CustomerID)
	VALUES
		((SELECT ID from Products Where PName = 'Dishmaker'),
		(SELECT ID from Customers Where Firstname = 'Meek')
		);

	-- Adding iPhone price at $200
INSERT INTO Products (PName, Price)
	VALUES
		('iPhone', 200.00);

	-- Adding customer Tina Smith

INSERT INTO Customers(Firstname, Lastname, CardNumber)
	VALUES
		('Tina', 'Smith', '46899736776738');

	-- Creating iPhone order for Tina Smith 

INSERT INTO Orders(ProductID, CustomerID)
	VALUES
		((SELECT ID from Products Where PName = 'iPhone'),
		(SELECT ID from Customers Where Firstname = 'Tina'));

	-- reporting all orders by Tina Smith

	SELECT * FROM Orders
		WHERE CustomerID = (SELECT CustomerID FROM Customers WHERE Firstname = 'Tina');
	
	-- reporting all revenue generated by sales of iPhone
	-- can't figure out how to do this one
	/*SELECT ID,PNAME, Price
		FROM Products AS P
		INNER JOIN Orders AS O ON P.ID = O.ProductID
		WHERE P.PName = 'iPhone'
		GROUP BY PName, ProductID, Price; 
		*/

	-- increasing iPhone price to $250
	UPDATE Products
	SET Price = 250.00
	WHERE PName = 'iPhone';